# docker-compose up -d --no-deps --build
# docker-compose stop

version: "3"
services:
    app:
        restart: always
        build:
            context: .
            dockerfile: .deploy/Dockerfile
        image: voltage:latest
        environment:
            - APP_ENV=prod
            - APP_PORT=${APP_PORT:-10011}
            - VOLTAGE_API_PORT=${VOLTAGE_API_PORT:-4000}
            - VOLTAGE_FRONTEND_PORT=${VOLTAGE_FRONTEND_PORT:-3000}
        ports:
            - "10011:10011"
