# docker-compose up -d --no-deps --build
# docker-compose stop

version: "3"
services:
    app:
        restart: always
        build:
            context: .
            dockerfile: .deploy/Dockerfile
        image: voltage:latest
        environment:
            - APP_ENV=prod
            # - APP_PORT=${APP_PORT:-8080}
            # - APP_BASE_URL=${APP_BASE_URL:""}
            # - APP_BASE_PATH=${APP_BASE_PATH:"/"}
            # - VOLTAGE_API_PORT=${VOLTAGE_API_PORT:-4000}
        ports:
            - "8080:8080"
